export const Actions = {
    INPUT_RECEIVED: "INPUT_RECEIVED",
    TRANSFORM_ADDED: "TRANSFORM_ADDED",
    REMOVE_TRANSFORM: "REMOVE_TRANSFORM",
    CHANGE_TRANSFORM_TYPE: "CHANGE_TRANSFORM_TYPE",
    INPUT_ENCODING_CHANGED: "INPUT_ENCODING_CHANGED",
    OUTPUT_ENCODING_CHANGED: "OUTPUT_ENCODING_CHANGED",
    TRANSFORM_OPTIONS_CHANGED: "TRANSFORM_OPTIONS_CHANGED"
};
